############# Croatian navigation ##############

# main menu

[[main]]
name = "O Namaa"
url = "o-nama/"
weight = 1

[[main]]
name = "Usluge"
url = "usluge/"
weight = 2

[[main]]
name = "Vijesti"
url = "vijesti/"
weight = 3

[[main]]
name = "Kriptovalute"
url = "kriptovalute/"
weight = 4

[[main]]
name = "Investiranje"
url = "investiranje/"
weight = 5


[[main]]
name = "Kontakt"
url = "kontakt/"
weight = 7

#[[main]]
#hasChildren = true
#name = "Pages"
#weight = 8

#[[main]]
#name = "Project"
#parent = "Pages"
#url = "project/"

#[[main]]
#name = "Pricing"
#parent = "Pages"
#url = "pricing/"

# footer menu
#[[footer]]
#name = "Pravna Pitanja"
#url = "#"
#weight = 1

#[[footer]]
#name = "Sitemap"
#url = "#"
#weight = 2

[[footer]]
name = "Politika Privatnosti"
url = "politika-privatnosti"
weight = 1

#[[footer]]
#name = "Uvjeti Korištenja"
#url = "#"
#weight = 2
